const SITE_INDEX=[
  [
    "【実物文書】PTA配布文書",
    "actual-pta-documents.html",
    "全国の学校・PTAから収集した実物の配布文書を整理。入会案内、会則、会費徴収文書、個人情報関連書類などを資料として公開します。"
  ],
  [
    "行政資料整理",
    "administrative-materials.html",
    "通知、行政回答、公文書、要綱、会計基準を読む際の確認ポイントを整理します。"
  ],
  [
    "質問類型ガイド",
    "answer-type-guide.html",
    "教育委員会回答DBで使っているA〜Gの質問類型を整理するガイドです。"
  ],
  [
    "教育委員会向け監査",
    "audit/board.html",
    "方針、通知、個人情報、教職員関与、監査耐性を点検します。"
  ],
  [
    "監査システム",
    "audit/index.html",
    "PTA運営の入会、個人情報、会費徴収、教職員関与、学校媒体利用を質問形式で点検する簡易監査アプリです。"
  ],
  [
    "保護者向け監査",
    "audit/parent.html",
    "入会意思、会費、個人情報、非会員児童の扱いを点検します。"
  ],
  [
    "学校管理職向け監査",
    "audit/principal.html",
    "校内事務、教職員関与、学校徴収金、個人情報、学校HP・配布物の扱いを点検します。"
  ],
  [
    "教育委員会向け10項目チェック",
    "board-checklist.html",
    "教育委員会・学校がPTA運営の公私分離、入会意思確認、個人情報、会費徴収、教職員関与を点検するための10項目チェックリストです。"
  ],
  [
    "教育委員会の回答",
    "board-responses.html",
    "全国教育委員会等への照会回答を、自治体別・質問類型別・全文アコーディオンで確認できるデータベースです。"
  ],
  [
    "判例整理",
    "cases.html",
    "PTA関連の裁判例・行政実例を、事実関係、判断部分、射程の限界に分けて整理します。"
  ],
  [
    "引用・確認手順",
    "citation-guide.html",
    "PTA適正化推進委員会サイトの資料を引用・転載・申入書に利用する前の確認手順と注記例を整理します。"
  ],
  [
    "主張・根拠・資料対応表",
    "claim-evidence-ledger.html",
    "サイト内の主要な主張を、確認対象となる法令・資料・関連ページに対応させる一覧です。"
  ],
  [
    "適正運用比較マトリクス",
    "comparison-matrix.html",
    "PTA運営の危険な運用例、適正化の方向、確認資料、関連ページを横並びで整理します。"
  ],
  [
    "【消費者庁】PTAは事業者",
    "consumer-agency-pta-business.html",
    "消費者庁の運用上、PTAが消費者契約法における「事業者」に該当することの整理。消費者契約法の適用関係を解説します。"
  ],
  [
    "委任があれば校務",
    "delegation-school-duty.html",
    "「PTAから委任があれば校務になる」という運用論の検討。委任契約の限界と校務範囲の法的制約を整理します。"
  ],
  [
    "PTA運営適正化診断",
    "diagnosis-pta-operation.html",
    "PTA運営の法的適正性を5軸で診断するセルフチェックツールの解説。立場別（保護者・PTA役員・学校管理職）の点検項目を整理します。"
  ],
  [
    "公文書開示請求準備キット",
    "disclosure-request-kit.html",
    "PTA運営適正化に関して、学校・教育委員会側の文書を確認するための開示請求準備ページです。"
  ],
  [
    "ご支援・寄付",
    "donate.html",
    "PTA適正化推進委員会の全国照会、公文書開示、資料整理、情報発信を継続するための支援ページです。"
  ],
  [
    "公立学校におけるPTA業務の「職務専念義務免除」運用の法理的破綻と組織的完全分離に関する緊急提言書",
    "duty-exemption-collapse.html",
    "教職員の職務専念義務免除運用の法理的破綻を整理し、学校とPTAの組織的完全分離を求める緊急提言書。"
  ],
  [
    "教委・学校用ガイドライン",
    "edu.html",
    "教育委員会・学校管理職が参照すべきPTA適正化のためのガイドライン。公私分離・職務専念義務・個人情報保護の観点から整備しています。"
  ],
  [
    "教育委員会の法的見解",
    "edu-board-legal-view.html",
    "全国の教育委員会が公式に示してきたPTAに関する法的見解を整理。任意加入原則、個人情報保護、職務専念義務に関する見解を一覧化します。"
  ],
  [
    "証拠整理台帳",
    "evidence-ledger.html",
    "入会、個人情報、会費、校務分掌、学校媒体などの原資料を論点別に整理する台帳ページです。"
  ],
  [
    "根拠マップ",
    "evidence-map.html",
    "PTA問題の5大論点ごとに、読むべきページ、原関連資料案内、確認すべき資料を整理した根拠マップです。"
  ],
  [
    "10枚で説明するPTA適正化",
    "explain-deck.html",
    "PTA適正化の要点を10枚のスライド風HTMLで説明します。"
  ],
  [
    "施設利用・学校HP",
    "facilities.html",
    "学校施設、学校HP、配布物、コピー機等をPTAが利用する場合の公私分離と公平性を整理します。"
  ],
  [
    "よくある質問",
    "faq.html",
    "PTAの自動加入、学校からPTAへの名簿提供、会費徴収、校務分掌、教育委員会への照会などの入口をFAQ形式で整理します。"
  ],
  [
    "学校徴収金・PTA会費代理徴収問題の統治構造論",
    "fee-collection-governance.html",
    "学校徴収金とPTA会費代理徴収の問題を、統治構造論（公私分離・財政法・民主的統制）の観点から分析します。"
  ],
  [
    "【提言】PTA会費の代理徴収",
    "fee-collection-proposal.html",
    "学校によるPTA会費の代理徴収について、その法的位置づけと適正化のための提言を整理します。"
  ],
  [
    "会費徴収",
    "fee-collection.html",
    "PTA会費、学校徴収金、一括引落、督促、返金、責任主体の分離を整理します。"
  ],
  [
    "教育委員会・学校へ",
    "guide-board.html",
    "教育委員会・学校向けに、公私分離、職務専念義務、個人情報、学校徴収金、学校HP・施設利用の是正方針を整理します。"
  ],
  [
    "保護者の方へ",
    "guide-parent.html",
    "PTA加入・会費・個人情報について保護者向けに整理します。任意加入、会費徴収、学校からPTAへの情報提供、非会員児童の扱いを確認できます。"
  ],
  [
    "PTA役員の方へ",
    "guide-pta.html",
    "PTA役員向けに、会則、会員名簿、会費徴収、学校との委託関係、教職員関与の整理方法を示します。"
  ],
  [
    "研究者・記者の方へ",
    "guide-research.html",
    "研究者・記者向けに、教育委員会回答、添付Excel、PDF原本、法制度整理への導線をまとめます。"
  ],
  [
    "PTA適正化ロードマップ",
    "implementation-roadmap.html",
    "PTA運営を公私分離、加入意思確認、個人情報、会費徴収、教職員関与の順に点検・是正するための実務ロードマップです。"
  ],
  [
    "トップ",
    "index.html",
    "PTA問題を一次資料と制度で整理する研究サイトです。入会手続、個人情報、会費徴収、教職員関与、教育委員会回答を横断的に確認できます。"
  ],
  [
    "面談・電話記録テンプレート",
    "interview-record-template.html",
    "教育委員会・学校・PTAとの面談や電話内容を、後から検証できる形で記録するためのテンプレートです。"
  ],
  [
    "論点ナビゲーター",
    "issue-navigator.html",
    "PTA問題を立場・論点・必要資料から探せるナビゲーションページです。入会、個人情報、会費、教職員関与、学校媒体を整理します。"
  ],
  [
    "論考・調査報告",
    "journal.html",
    "PTA問題に関する制度分析、行政資料分析、研究ノートを掲載するページです。"
  ],
  [
    "川崎市：PTA業務の校務化の無効性",
    "kawasaki-school-duty-invalidity.html",
    "川崎市におけるPTA業務の校務化運用について、その法的無効性を制度面と実態面から整理します。"
  ],
  [
    "法制度マップ",
    "law-map.html",
    "PTA問題に関係する民法、個人情報保護法、地方公務員法、学校教育法、社会教育法等の論点を整理します。"
  ],
  [
    "【論考】PTAの法的構造と教育行政の監督責任",
    "legal-structure-supervision.html",
    "PTAの法的構造（任意団体・社会教育関係団体）の整理と、教育行政（教育委員会）の指導監督責任を法理から論じます。"
  ],
  [
    "公立学校におけるPTA業務従事と地方公務員法第35条「職務専念義務」の法的抵触に関する包括的論考",
    "lpsa-art35-conflict.html",
    "公立学校教職員のPTA業務従事と、地方公務員法第35条の職務専念義務との抵触を、判例（茅ヶ崎市職員派遣事件等）に即して論じる包括論考。"
  ],
  [
    "入会手続・みなし加入",
    "membership.html",
    "PTA入会手続、みなし加入、入会意思確認、退会自由、会費請求の前提を整理します。"
  ],
  [
    "【文科省】PTA業務は公務ではない",
    "mext-pta-not-public.html",
    "文部科学省の見解および関連通知の整理から、PTA業務が公務（学校の職務）に含まれないことを明確化します。"
  ],
  [
    "論考・資料索引",
    "research-index.html",
    "Googleサイトから整理した論考・研究資料28本を、資料整理済み・追加確認が必要・関連資料案内ページに分類して確認できます。"
  ],
  [
    "全国資料館",
    "archive.html",
    "教育委員会回答、添付Excel、PDF原本、分析ページへの導線を整理した資料館です。"
  ],
  [
    "非会員情報の取得不可能性",
    "non-member-info-impossibility.html",
    "PTAが入会届を整備しない限り「誰が会員か」を把握できないという構造的事実から、学校による名簿流用の違法性を整理します。"
  ],
  [
    "PTA問題 一枚要約",
    "one-page-brief.html",
    "PTA問題を初見の教育委員会・学校・保護者に説明するための一枚要約ページです。印刷・共有を想定しています。"
  ],
  [
    "【論考】オプトアウトの無効性",
    "optout-invalidity-article.html",
    "PTA入会におけるオプトアウト（みなし加入）方式の法的無効性を、民法第522条・消費者契約法から論じる総合論考。"
  ],
  [
    "オプトアウト加入の無効性",
    "optout-invalidity.html",
    "オプトアウト方式によるPTA加入の法的無効性。入会申込書なき自動加入が引き起こす連鎖的な違法状態を整理します。"
  ],
  [
    "教職員関与",
    "personnel.html",
    "PTA事務に対する教職員関与、勤務時間、校務分掌、職務専念義務の論点を整理します。"
  ],
  [
    "印刷・提出用ツールキット",
    "print-toolkit.html",
    "一枚要約、比較表、チェックリスト、引用確認手順など、印刷・提出用ページをまとめます。"
  ],
  [
    "個人情報提供",
    "privacy.html",
    "学校からPTAへの児童・保護者情報提供、本人同意、利用目的、非会員情報の扱いを整理します。"
  ],
  [
    "PTA業務と職務専念義務",
    "pta-duty-concentration.html",
    "公立学校教職員がPTA業務に従事することと地方公務員法第35条「職務専念義務」の関係。茅ヶ崎市職員派遣事件等の判例を踏まえ整理します。"
  ],
  [
    "PTA問題の5大論点",
    "pta-issues-overview.html",
    "PTA問題を初めて読む人向けに、入会意思確認、個人情報提供、会費徴収、教職員関与、公的媒体・施設利用の5大論点を整理します。"
  ],
  [
    "「公益性」と言う名の罠",
    "public-interest-trap.html",
    "PTA業務の正当化に用いられる「公益性」の抗弁が招く自己矛盾と二重の違法性を法理に即して論じます。"
  ],
  [
    "印刷・引用・提出時の注記",
    "public-use-notes.html",
    "サイト本文を印刷・引用・提出する際の注記例と注意事項を整理します。"
  ],
  [
    "読み方ガイド",
    "reading-guide.html",
    "PTA適正化推進委員会サイトの目的別導線を整理し、初見、教育委員会、保護者、研究・報道向けの読み順を示します。"
  ],
  [
    "総合分析レポート",
    "report.html",
    "PTA問題を、加入意思確認、個人情報、会費徴収、教職員関与、学校資源利用の構造問題として分析します。"
  ],
  [
    "住民監査請求準備ノート",
    "resident-audit-prep.html",
    "PTA会費徴収、教職員関与、任意団体事務従事を住民監査請求の観点で整理するための準備ノートです。"
  ],
  [
    "自治体回答読み解きガイド",
    "response-analysis-guide.html",
    "全国の教育委員会回答を、回答類型・質問項目・根拠状態に分けて整理するための実務ガイドです。"
  ],
  [
    "自治体回答インデックス",
    "response-index.html",
    "教育委員会回答DBの自治体別簡易索引です。自治体名から検索条件付きで回答DBへ移動できます。"
  ],
  [
    "PTA運営リスクヒートマップ",
    "risk-heatmap.html",
    "PTA運営で早期確認が必要な論点を、重大度と確認資料の観点から整理します。"
  ],
  [
    "校務分掌とPTA業務",
    "school-duties-vs-pta.html",
    "校務分掌制度とPTA業務の関係を整理し、任意団体業務を校務化することの法的不可能性を論じます。"
  ],
  [
    "学校徴収金管理及びPTA業務代行における法的整合性の欠落と構造的違法性に関する包括的研究報告書",
    "school-fee-collection-illegality.html",
    "学校徴収金管理とPTA業務代行における法的整合性の欠落、および構造的違法性を網羅的に整理する研究報告書。"
  ],
  [
    "サイトマップ",
    "sitemap.html",
    "PTA適正化推進委員会サイトの公開ページ一覧です。"
  ],
  [
    "資料確認方針",
    "source-policy.html",
    "PTA適正化推進委員会サイトにおける一次資料優先、根拠状態ラベル、未確認情報の扱い、引用時の注意を整理します。"
  ],
  [
    "立場別ブリーフ",
    "stakeholder-briefs.html",
    "教育委員会、学校、PTA役員、保護者、議員、報道向けに、読む順番と伝える要点を整理します。"
  ],
  [
    "3分でわかるPTA適正化",
    "start-here-3min.html",
    "初見者向けに、PTA適正化の出発点と確認すべき論点を短く整理します。"
  ],
  [
    "教育委員会提出パック",
    "submission-kit.html",
    "教育委員会・学校へPTA運営適正化を照会・提出する前に、論点、添付資料、確認事項を整理する実務用ページです。"
  ],
  [
    "【総括】PTA適正化推進委員会",
    "summary-pta-committee.html",
    "PTA適正化推進委員会の総括的論考。完全オプトイン化、組織・金銭・情報の完全分離という三本柱を法理から整理します。"
  ],
  [
    "PTA問題 用語集",
    "term-glossary.html",
    "PTA適正化の議論で使う主要用語を、断定しすぎず、確認すべき資料とあわせて整理する用語集です。"
  ],
  [
    "【考察】第三者提供同意の問題点",
    "third-party-consent-issue.html",
    "個人情報保護法における第三者提供同意の問題点を、PTAへの名簿提供事例に即して考察します。包括同意の限界とオプトアウト不適用を整理します。"
  ],
  [
    "時系列整理シート",
    "timeline-builder.html",
    "照会、回答、面談、開示請求、是正対応を時系列で整理するための実務シートです。"
  ],
  [
    "構造図で見るPTA問題",
    "visual-overview.html",
    "PTA問題を、学校・PTA・保護者・教育委員会の関係、情報・金銭・労務の流れから視覚的に整理するページです。"
  ],
  [
    "【論考】教職員の働き方改革とPTA会費代理徴収の限界",
    "work-style-reform-limit.html",
    "教職員の働き方改革の観点から、形式的厳格化（業務委託契約・個別同意）によるPTA会費代理徴収維持の限界を論じます。"
  ],
  [
    "横浜市教育委員会 通知 学教第1965号",
    "yokohama-notice-1965.html",
    "横浜市教育委員会が発出した学教第1965号通知の整理。入会届（オプトイン）の必須化と、本人同意なき名簿提供の禁止を明示した重要通知です。"
  ],
  [
    "【適正化状況】横浜市PTA",
    "yokohama-status.html",
    "横浜市内のPTA適正化の進捗状況を整理。学教第1965号通知以降の各校・各区の対応状況を継続的にトラッキングします。"
  ]
];
function initMobile(){const b=document.getElementById("hamburger"),o=document.getElementById("mobileOverlay"),c=document.getElementById("closeOverlay");if(!b||!o)return;b.onclick=()=>{o.classList.add("is-open");b.setAttribute("aria-expanded","true")};c&&(c.onclick=()=>{o.classList.remove("is-open");b.setAttribute("aria-expanded","false")});}
function initDropdowns(){document.querySelectorAll(".nav-item.has-dropdown>.nav-link").forEach(link=>{link.addEventListener("click",e=>{e.preventDefault();const item=link.closest(".nav-item");document.querySelectorAll(".nav-item.is-open").forEach(x=>{if(x!==item)x.classList.remove("is-open")});item.classList.toggle("is-open")})});document.addEventListener("click",e=>{if(!e.target.closest(".nav-item"))document.querySelectorAll(".nav-item.is-open").forEach(x=>x.classList.remove("is-open"))})}
function initSearch(){document.querySelectorAll(".search-input").forEach(input=>{const dd=input.parentElement.querySelector(".search-results-dropdown");if(!dd)return;input.addEventListener("input",()=>{const q=input.value.trim();if(q.length<2){dd.classList.remove("is-open");return}const hits=SITE_INDEX.filter(x=>(x[0]+x[2]).includes(q)).slice(0,8);const prefix=location.pathname.includes("/audit/")?"../":"";dd.innerHTML=hits.length?hits.map(x=>`<a class="srd-item" href="${prefix}${x[1]}"><div class="srd-item-title">${x[0]}</div><div class="srd-item-desc">${x[2]}</div></a>`).join(""):`<div class="srd-empty">該当なし</div>`;dd.classList.add("is-open")});});}

function initIssueNavigator(){document.querySelectorAll('[data-navigator]').forEach(shell=>{const buttons=shell.querySelectorAll('[data-filter]');const cards=shell.querySelectorAll('.navigator-card');buttons.forEach(btn=>btn.addEventListener('click',()=>{const f=btn.dataset.filter;buttons.forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');cards.forEach(card=>{const tags=(card.dataset.tags||'').split(/\s+/);card.classList.toggle('is-hidden',f!=='all'&&!tags.includes(f));});}));});}
function initCopyButtons(){document.querySelectorAll('[data-copy-target]').forEach(btn=>btn.addEventListener('click',async()=>{const el=document.getElementById(btn.dataset.copyTarget);if(!el)return;const txt=el.innerText||el.textContent||'';try{await navigator.clipboard.writeText(txt);btn.classList.add('copied');btn.textContent='コピー済み';setTimeout(()=>{btn.classList.remove('copied');btn.textContent='コピー'},1600);}catch(e){btn.textContent='選択してコピー';}}));}
function initFaqSearch(){const input=document.getElementById('faqSearch');const list=document.querySelector('[data-faq-list]');if(!input||!list)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();list.querySelectorAll('.faq-item').forEach(item=>{const t=(item.textContent+' '+(item.dataset.keywords||'')).toLowerCase();item.classList.toggle('is-hidden',q&& !t.includes(q));});});}

document.addEventListener("DOMContentLoaded",()=>{initMobile();initDropdowns();initSearch();initIssueNavigator();initCopyButtons();initFaqSearch();});
